Use Customer_Behaviour; 
Select TOP 5 * from CustomerTable;

-- what is total revenue generated by male vs female customers?
Select gender, SUM(purchase_amount) as Revenue
from CustomerTable
GROUP BY gender;

-- Which customer used a discount but still spent more than average purchase amount?
Select customer_id, purchase_amount
from CustomerTable
Where discount_applied = 'Yes' and purchase_amount > (Select AVG(purchase_amount) from CustomerTable);

-- Which are the top products with the highest average review rating?
Select TOP 10 item_purchased, Round(AVG(review_rating),2) as Average_review
from CustomerTable
GROUP BY item_purchased ORDER BY Average_review DESC;

-- Compare the average purchase amount between standard and express shipping?
Select shipping_type, AVG(purchase_amount) as 'Average purchase amount'
from CustomerTable
Where shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Do subcribed customers spend more? Compare avearage spend and total revenue between subscribers and non subscribers?
Select CASE
When subscription_status = 'Yes' then 'Subscribers'
else 'Non Subscriber'
END as 'Subscription Status', COUNT(customer_id) as 'Total Customers', SUM(purchase_amount) as 'Total Revenue', Round(AVG(purchase_amount),2) 'Average spend'
From CustomerTable
Group By subscription_status;

-- Which 5 products have the highest percentage of purchases with discount applied?
Select TOP 5 item_purchased, 100 * SUM(Case When discount_applied = 'Yes' then 1 ELSE 0 END)/Count(*) as discount_rate
from CustomerTable
Group by item_purchased
Order by discount_rate DESC;

-- Segement customer's into new, returning and loyal based on their total number of purchases and show the count of each segment?
With customer_type as (
Select customer_id, 
CASE
	When previous_purchases = 1 Then 'New'
	When previous_purchases BETWEEN 2 AND 10 Then 'Returning'
	Else 'Loyal'
End as customer_segment
From CustomerTable )

Select customer_segment, Count(*) as 'number_of_customers'
From customer_type
Group by customer_segment;

-- What are the top 3 most purchased product within each category?
Select ranks, category, item_purchased, total_purchase
FROM 
	(Select category, item_purchased, COUNT(item_purchased) as total_purchase, 
	ROW_NUMBER() Over (Partition by category Order by Count(item_purchased) DESC) as ranks
	from CustomerTable 
	Group by category, item_purchased ) t
where ranks <= 3
Order by category

-- Are customers who are repeat buyers(more than 5 times) also likely to subscribe?
Select subscription_status, Count(customer_id) as repeat_customers
From CustomerTable
where previous_purchases > 5
Group by subscription_status;

-- What is the revenue contribution from each age group?
Select age_group, SUM(purchase_amount) as revenue
From CustomerTable
Group by age_group
Order by revenue DESC;